name: Test Code Syntax/Compile Errors
on: [push]
jobs:
  test-syntax:
    runs-on: ubuntu-latest
    steps:
      - run: pip install -r requirements.txt
      - run: pytest
      - run: python3 -m compileall . -q

      